Make implementation_type public in container types
This is used by jsoncons::type_traits::detail::basic_json_t in certain
circumstances, and ICC does not like that it is not publicly accessible.

Fixes compilation errors like:

jsoncons/basic_json.hpp(49):
error #525: type "jsoncons::json_object<KeyT, Json,
std::enable_if<std::is_same<Json::implementation_policy::key_order,
jsoncons::sort_key_order>::value, void>::type>::implementation_policy
[with KeyT=std::basic_string<char, std::char_traits<char>,
std::allocator<char>>, Json=jsoncons::basic_json<char,
jsoncons::sorted_policy, std::allocator<char>>]" (declared at line 541
of "jsoncons/json_container_types.hpp")
is an inaccessible type (allowed for cfront compatibility)
basic_json_t = basic_json<typename T::char_type,typename
T::implementation_policy,typename T::allocator_type>;
detected during:
    instantiation of type
    "jsoncons::type_traits::detail::basic_json_t<
    jsoncons::json_object<std::basic_string<char,
    std::char_traits<char>, std::allocator<char>>,
    jsoncons::basic_json<char, jsoncons::sorted_policy,
    std::allocator<char>>, void>>" at line 182 of
    "jsoncons/more_type_traits.hpp"