Fix for clang 20
Fixes the following clang 20 error:

```
jsoncons/basic_json.hpp:5571:34: error: identifier '_ojson' pre
ceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
```